### ISSUE TITLE
Bug: Snowy Fort Gate open without the check

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#23]
### What happened?

Snowy Fort Gate opened as normal. Even tho it shouldn't as it's a check:
![20240613211537_1](https://github.com/ArchipelaGOAL/Archipelago/assets/5995327/360b5b45-a595-4f45-af18-8916bdc5063a)

### What were the expected results?

For the Snowy Fort Gate to only be open once you get the check.

### Software

While playing

**Comment by massimilianodelliubaldini** [comment]
"As normal" meaning, you hit the button with Flut Flut? And the camera panned away, showing the gate opening?

**Comment by jacobmix** [comment]
"As normal" Like in the vanilla game. Was on foot i'm pretty sure as when you land you automatically get off Flut-Flut.
Ran to the power cell. Picked it up. After that the gate opening cutscene played (like vanilla), could see the gate moved underground, and i went to the gate entrance, and it was open.

**Comment by massimilianodelliubaldini** [comment]
I've got this figured out. 

The problem is I only modified the initialization of the door, when it first loads in after a respawn, walk into Snowy Mountain, etc. But I didn't modify the _button_ that activates the door, nor did I modify _either_ of their state machines. So pressing on the button acted like it did in vanilla... because I hadn't changed it from vanilla.

The solution was to modify all three of these objects (the button, the door, and the gears (just for aesthetic reasons)). So the button is now decoupled from the door and the gears - it triggers the cutscene, but none of the objects move. When you receive the fort gate item, that is when the gears turn and the door slides down (they enter their activated states). Finally, when you load in, the gears and the door should go directly to their intended state (open/closed or idle/stopped) so you don't have to watch them turn and slide all over again.
