### ISSUE TITLE
Logic Questions/Concerns

### ISSUE THREAD

**Issue by isthatbrian** [ArchipelaGOAL/Archipelago#34]
### What happened?

I have really been enjoying playing Jak and Daxter in archipelago. You’ve done some incredible work so far. I just wanted to mention some logic that I think is perhaps incorrect. I have looked through the logic and done several playthroughs before making this post. Take these with a grain of salt as reading through the files is challenging and I may have missed something or incorrectly read something.

1. It looks like the logic ignores the high jumps from timing an X press on Jump Dive and Roll Jump. It’s tricky because they require timing and not all players may know about the tech, but they open up a few of out-of-logic checks if not accounted for such as orb Cache in Sandover. It’s probably fine imo.

2. LPC: Raise the Chamber currently only needs Jump Dive for logic, but you need Triple Jump to acquire the cell outside.

3. Orb Cache in Misty Island needs can_fight but not kick. The bone bridge only falls with jump kick and Jump Dive. Just Kick doesn’t work unless it’s in midair. I could be wrong on this though.

4. Scout fly near green eco cliff in Sentinel needs Can Jump Higher

5. Does Boggy require double jump? It seems that after I got the pontoons everything in Boggy is out of logic according to Universal Tracker. Even the scout flies are out of logic

6. LPC Climb the Slide tube should have the same ability requirement as Reach the Bottom of the City. It appears that it doesn’t. Also you can get the platform at the bottom with just single jump + jump dive but you may not want to make that the logic.

7. Final Boss should have punch required imo. I think it just has "can_fight"

Hopefully this can aid in further development. Thanks and let me know if anything is confusing!

### What were the expected results?

N/A

### Software

While playing

**Comment by isthatbrian** [comment]
Just got the Raise the Chamber with Roll Jump

**Comment by jacobmix** [comment]
> LPC: Raise the Chamber currently only needs Jump Dive for logic, but you need Triple Jump to acquire the cell outside.
> Just got the Raise the Chamber with Roll Jump

If you raise the chamber, and the lower it again. You can get it by with just jump dive.  
  
This is a bit outdated by now, but if you wanna help route move rando in more detail you can contribute like here: https://github.com/ArchipelaGOAL/Archipelago/issues/7  
Just boot up OpenGOAL in debug mode (under "Advanced"), and use R3>Game>Continue>Spawn-Location. Hit X>Start To teleport. L3 to spawn Zoomer/Flut-Flut when on the platform. Test everything as you'd like.

**Comment by massimilianodelliubaldini** [comment]
1. Yes, that was deliberate. I don't take into account the extra height gained coming out of a Jump Dive or a Roll Jump in case players aren't aware of it. Same applies to Extendeds/Boosteds (speedrun tech).
2. You don't necessarily need Triple Jump because you can reactivate the chamber, ride it back down, and the power cell will remain on it's roof back in LPC. Now I _thought_ the blue eco vent at the bottom would help you get that cell with Single Jump, but having tried it for a bit, it seems you need a little more than that. So I will modify that cell to require Double Jump OR Jump Kick OR Punch Uppercut, since all those techniques will get you on top.
3. I double checked myself, the bone bridges will drop to any attacking move, including Punch and Kick.
4. Yep, that ledge needs Crouch Jump or Double Jump, both of which are accounted for.
5. My rule for Boggy was to avoid forcing the player to take damage to cross the black tar swamps. So the very first black tar area with the bats floating above it, that needs any of the following: Double Jump, Jump Kick, or Punch Uppercut. Note, the scout fly box and locked crates in the "lobby" can be gotten with nothing but the free floating yellow eco nearby and some clever Goggle shots.
6. Jump Dive to activate that button requires Wiley Coyote-ing the very last step off the slide, and it was not consistent enough to keep in the rules.
7. Final Boss with Goggles only is not as intimidating as it seems. You can strategically line up the green eco monsters to shoot them with Goggles, you can wait out the red exploding orbs and wait for an opening, and you can dodge the yellow eco blast by just making your way downtown, walking fast. I also originally required Punch for this fight, but dropped it because the logic was trying shoehorn Punch into odds places and creating really bad chains to get it.
